import Mathlib.RingTheory.Spectrum.Prime.Topology

open TopologicalSpace Topology

variable (X : Type*) [TopologicalSpace X]

/--
The patch topology on a topological space `X` is generated by the open compact subsets of `X` and
the complements of them.
-/
def PatchTopology : TopologicalSpace X :=
  generateFrom ({ S : Set X | IsOpen S ∧ IsCompact S } ∪
    { S : Set X | ∃ O : Set X, IsOpen O ∧ IsCompact O ∧ S = Oᶜ })
